# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74329586b44c930d82fdfd901c8949bbb9490041767f9fceb63ca3292fa093bc2027d1434d8a128efd25e1ee130da195225816205c63d16d8283b8430d8710d9

test:
  secret_key_base: 1cb9ba4b345a8d714dd9aa574ddd8daaa40456980f31913c1d746ed2f25eef769ed01729c965ccb8634693d6e70593e9028d5204730d560e3fc4acf48d0f7a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b63f051f2baed5a7d3ebe22fc4ce1e37a6dfd60c95edf4ec991b2f342c9ee073409d06f939cca1961171a504e16b3ef035633059fe6fd3deebaf41d06ee008df
